### PR TITLE
 Add TravisCI configuration

### LINKED ISSUE #14: Add CI config to automatically verify new commits
I've noticed that there are already open issues for tests (#8 and #9), but at the moment there is no automatic verification so it won't be immediately visible if a new commit breaks the tests.

I think it's useful to see at a glance if there is some possible improvements to a pull request, both for the author and the repo maintainer. So I suggest configuring a free continuous integration service to improve the workflow.

### PR DESCRIPTION
**Pull request by theag3nt**
Added a configuration file and build badge for TravisCI which is a popular continuous integration service. It will run test for new commits with go 1.9, 1.10, 1.11 and the latest development version. Also checks if `gofmt` or `go vet` reports any possible improvements.

If you already have Travis set up for your account, just enable it for the repository. Otherwise follow the instructions on their site: https://docs.travis-ci.com/user/getting-started/#to-get-started-with-travis-ci

After merging, hopefully a new build will start automatically, but if not you can test the setup by adding a new commit or manually triggering a build on the `master` branch.

Fixes #14.

### CODE REVIEW

**Comment by IngCr3at1on** [comment]
This is some nice work...

I'm debating though whether it's better to provide backwards compatibility for Go 1.10 and 1.9 or to ensure that CI builds are always reproducible by leveraging the module support in Go 1.11 using the existing go.mod file.

Also you may notice that _currently_ there are no tests (that's absolutely my fault for building these tools against real bots rather than tests); to that end it would probably be a good idea to ensure that the examples build and run (I believe both mine and your examples return non-zeros on failure so this will still allow for some level of testing).

**Comment by theag3nt** [comment]
In Go's [release policy](https://golang.org/doc/devel/release.html#policy) it's stated that the last 2 releases are officially supported. At the moment that means 1.10 and 1.11. We could remove versions before 1.11, but 1.10 is still supported so there could be many people using it. Also, the module support is still opt-in in 1.11 and I think the CI builds should be testing all valid use cases.

So I propose to keep the current versions until there are known incompatibilities (e.g. features from newer Go versions), but add 1.11 with enabled module support to the tested setups. Older version could be removed gradually on every new Go release and after 1.13 (when all supported versions will have enabled module support) the build can be fully converted to modules.

As for the examples, they're currently ignored by default by the `go` tool because of the underscore in their directory name. I can add a build step to cover them too. But running them would be a kind of integration test and that would need some setup, credentials and another process which triggers events and a graceful exit. So I think executing the examples has a bit bigger scope and I'd vote for separate, well defined tests instead (probably only after there are some unit tests).

What do you think?

**Comment by theag3nt** [comment]
Also I think the whole repository should be in the same module, because as far as I know all packages in the repo belong together (see the intended definition in [the Go wiki](https://github.com/golang/go/wiki/Modules#modules)). And in the current state `go build` generates a `go.mod` file on the fly in the root directory anyway.

**Comment by IngCr3at1on** [comment]
> In Go's release policy it's stated that the last 2 releases are officially supported. At the moment that means 1.10 and 1.11. We could remove versions before 1.11, but 1.10 is still supported so there could be many people using it. Also, the module support is still opt-in in 1.11 and I think the CI builds should be testing all valid use cases.

> So I propose to keep the current versions until there are known incompatibilities (e.g. features from newer Go versions), but add 1.11 with enabled module support to the tested setups. Older version could be removed gradually on every new Go release and after 1.13 (when all supported versions will have enabled module support) the build can be fully converted to modules.

The main issue I have here is that simply running a `go get` does not in any-way ensure that the builds are reproducible and in fact is a recipe for CI to fail later. The proper compromise (that I personally didn't feel like doing) is to provide a dep config instead and have CI use this. If you want to do that I'll accept this but as it stands I'm firmly against the idea of `go get` being used directly for reproducible builds; this is a large reason for the design of go modules in the first place.

> As for the examples, they're currently ignored by default by the go tool because of the underscore in their directory name. I can add a build step to cover them too. But running them would be a kind of integration test and that would need some setup, credentials and another process which triggers events and a graceful exit. So I think executing the examples has a bit bigger scope and I'd vote for separate, well defined tests instead (probably only after there are some unit tests).

They're ignored if you attempt to build the entire repo/package yes but there's pretty much _no_ reason you should ever be attempting to build a stand-alone library in that manner; it would be entirely useless. Sadly though since I think all the exmples are blocking you're right that we can't test them directly so that is an issue. As for unit tests you'll find there are issues open for these lol

> Also I think the whole repository should be in the same module, because as far as I know all packages in the repo belong together (see the intended definition in the Go wiki).

While most of the package can be used together the intention is to decouple them as much as possible from each other so that they are mostly optional. That's not going to be the case of the commands package with regards to transport (that's a pretty hard requirement) but permissions for example are intended to be an optional add on; as will most other future packages that aren't currently present. In short, no the sub-module approach is definitely the way we want to continue. I might be open to changing the structure slightly if you have a good proposal but this is something that we'd want to discuss in great detail as it would break any backwards compatibility in the API (something I've already partially done by fixing the canonical paths so that's only a minor issue at this point...).

>  And in the current state go build generates a go.mod file on the fly in the root directory anyway.

Why would you ever build the root directory?

**Comment by IngCr3at1on** [comment]
I just enabled Travis in their web console so any new pushes should trigger a build.

**Comment by theag3nt** [comment]
> The main issue I have here is that simply running a `go get` does not in any-way ensure that the builds are reproducible and in fact is a recipe for CI to fail later. The proper compromise (that I personally didn't feel like doing) is to provide a dep config instead and have CI use this. If you want to do that I'll accept this but as it stands I'm firmly against the idea of `go get` being used directly for reproducible builds; this is a large reason for the design of go modules in the first place.

I also prefer reproducible builds, but I expect a CI build to cover the most common use cases and I think currently that includes not using Go modules as well. But let's remove non-module builds then.

What about the packages which do not have a `go.mod` (all except transport)? Do you plan to make a separate module for each package?
 
> They're ignored if you attempt to build the entire repo/package yes but there's pretty much _no_ reason you should ever be attempting to build a stand-alone library in that manner; it would be entirely useless.

That's probably an issue with documentation then. As a user I'm not able to tell at a glance that every subpackage in the repo is stand-alone and I need some special steps to use it (i.e. not a simple `go get`). I still don't really understand how that makes building all packages in the repo useless, but let's try another direction.

What is your preferred approach for building/testing the repo? My usual solution (as you can see in the proposed `.travis.yml`) is to run build/tests on all subpackages, and looks like it's not what you want.

> Sadly though since I think all the exmples are blocking you're right that we can't test them directly so that is an issue. We should however still attempt to build them, individually. As for unit tests you'll find there are issues open for these lol
 
Sure, I'll add a build step for the examples.
 
> While most of the package can be used together the intention is to decouple them as much as possible from each other so that they are mostly optional. That's not going to be the case of the commands package with regards to transport (that's a pretty hard requirement) but permissions for example are intended to be an optional add on; as will most other future packages that aren't currently present. In short, no the sub-module approach is definitely the way we want to continue. I might be open to changing the structure slightly if you have a good proposal but this is something that we'd want to discuss in great detail as it would break any backwards compatibility in the API (something I've already partially done by fixing the canonical paths so that's only a minor issue at this point...).

I understand the intention for decoupling the packages, but it's not entirely clear for me why that leads to each package being a separate module. Would you like to version them separately? Or use different versions of the same dependencies in separate packages?

As not referenced packages are not compiled into the resulting binary, the only advantage of separate modules I see on a first glance is fewer downloaded dependencies on a build. But I don't really use modules myself yet, is there something I'm missing?

> Why would you ever build the root directory?

I meant the repo root, and building with that as the working directory. I could've used any other directory, but that makes the most sense for me.

**Comment by IngCr3at1on** [comment]
> What about the packages which do not have a go.mod (all except transport)? Do you plan to make a separate module for each package?

yeah there's just several missing at the moment like I forgot to add one for commands when I added it.

> That's probably an issue with documentation then. As a user I'm not able to tell at a glance that every subpackage in the repo is stand-alone and I need some special steps to use it (i.e. not a simple go get).

yes we are in great need of docs I just get in a habit of writing things to use them and then have issues going back and adding those things, it's definitely on my mental check list.

> What is your preferred approach for building/testing the repo? My usual solution (as you can see in the proposed .travis.yml) is to run build/tests on all subpackages, and looks like it's not what you want.

Normally I would agree however in the case of multiple modules I think it's best to have CI attempt to build these individually (as part of the same build of course); to that end I think what you've done here is great.

> Would you like to version them separately? Or use different versions of the same dependencies in separate packages?

This is exactly it yes, it should be possible for one module to be updated while others are not and in most cases it should not be a requirement that all users update; very similar to your intention of supporting previous versions of go this is an attempt at ensuring that the botkit packages remain compatible with each other (at least with similar versions, it's likely some versions will drift more than others). Sadly I'm having issues thinking of a good example of a package/repo which follows this design pattern but I know a few exist lol.

> But I don't really use modules myself yet, is there something I'm missing?

Mainly better dependency control, if you haven't read https://research.swtch.com/vgo it's a good start and covers more arguments for modules in better ways than I ever could lol

> I meant the repo root, and building with that as the working directory. I could've used any other directory, but that makes the most sense for me.

This seems a little weird to me as I would only ever build the binary that was importing the the package or sub-packages; a binary of a library to me is kind of silly in Go because generally Go doesn't use dynamic linked libs but instead statically links them in the binary.

**Comment by IngCr3at1on** [comment]
thanks @theag3nt!

**Comment by theag3nt** [comment]
> Normally I would agree however in the case of multiple modules I think it's best to have CI attempt to build these individually (as part of the same build of course); to that end I think what you've done here is great.

A separate build step for every package could be an improvement then, but the disadvantage that the list of packages have to be maintained in the build config when packages come and go.

> This is exactly it yes, it should be possible for one module to be updated while others are not and in most cases it should not be a requirement that all users update; very similar to your intention of supporting previous versions of go this is an attempt at ensuring that the botkit packages remain compatible with each other (at least with similar versions, it's likely some versions will drift more than others). 

I see. Then the situation is a bit more complicated than I first thought. 🙂 

> Mainly better dependency control, if you haven't read https://research.swtch.com/vgo it's a good start and covers more arguments for modules in better ways than I ever could lol

Yeah, it's on my reading backlog, I should really go through all those posts.

> This seems a little weird to me as I would only ever build the binary that was importing the the package or sub-packages; a binary of a library to me is kind of silly in Go because generally Go doesn't use dynamic linked libs but instead statically links them in the binary.

In this context I use the word "build" as "make sure it compiles / make sure the tests pass". So we're not really interested in the end results of a `go build` for example, only that the process completes without error.

> thanks @theag3nt!

I'm glad I was able to help. 🙂

**Comment by theag3nt** [comment]
I've just noticed, that the build badge doesn't work. I'll add a quick fix in a moment.

**Pull request merged**
